"""Integration test cases for the raceplans route."""
import os
from typing import Any, Dict, List
import uuid

from aiohttp import hdrs
from aiohttp.test_utils import TestClient as _TestClient
from aioresponses import aioresponses
import jwt
import pytest
from pytest_mock import MockFixture

from race_service.models import Raceplan


@pytest.fixture
def token() -> str:
    """Create a valid token."""
    secret = os.getenv("JWT_SECRET")
    algorithm = "HS256"
    payload = {"identity": os.getenv("ADMIN_USERNAME"), "roles": ["admin"]}
    return jwt.encode(payload, secret, algorithm)  # type: ignore


@pytest.fixture
async def request_body() -> dict:
    """Create a mock request_body object."""
    return {"event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95"}


@pytest.fixture
async def event() -> Dict[str, Any]:
    """An event object for testing."""
    return {
        "id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "name": "Oslo Skagen sprint",
        "competition_format": "Individual Sprint",
        "date_of_event": "2021-08-31",
        "time_of_event": "09:00:00",
        "organiser": "Lyn Ski",
        "webpage": "https://example.com",
        "information": "Testarr for å teste den nye løysinga.",
    }


@pytest.fixture
async def race_config() -> List[Dict[str, Any]]:
    """A race_config used in competition_format."""
    return [
        {
            "max_no_of_contestants": 8,
            "rounds": ["Q", "F"],
            "no_of_heats": {
                "Q": {"A": 1},
                "F": {"A": 1, "B": 0, "C": 0},
            },
            "from_to": {
                "Q": {"A": {"F": {"A": "ALL", "B": 0}}, "C": {"F": {"C": 0}}},
            },
        },
        {
            "max_no_of_contestants": 16,
            "rounds": ["Q", "F"],
            "no_of_heats": {
                "Q": {"A": 2},
                "F": {"A": 1, "B": 1, "C": 0},
            },
            "from_to": {
                "Q": {"A": {"F": {"A": 4, "B": "REST"}}, "C": {"F": {"C": 0}}},
            },
        },
        {
            "max_no_of_contestants": 24,
            "rounds": ["Q", "S", "F"],
            "no_of_heats": {
                "Q": {"A": 3},
                "S": {"A": 2, "C": 0},
                "F": {"A": 1, "B": 1, "C": 1},
            },
            "from_to": {
                "Q": {"A": {"S": {"A": 5, "C": 0}, "F": {"C": "REST"}}},
                "S": {"A": {"F": {"A": 4, "B": "REST"}}, "C": {"F": {"C": 0}}},
            },
        },
        {
            "max_no_of_contestants": 32,
            "rounds": ["Q", "S", "F"],
            "no_of_heats": {
                "Q": {"A": 4},
                "S": {"A": 2, "C": 2},
                "F": {"A": 1, "B": 1, "C": 1},
            },
            "from_to": {
                "Q": {"A": {"S": {"A": 4, "C": "REST"}}},
                "S": {"A": {"F": {"A": 4, "B": "REST"}}, "C": {"F": {"C": 4}}},
            },
        },
        {
            "max_no_of_contestants": 40,
            "rounds": ["Q", "S", "F"],
            "no_of_heats": {
                "Q": {"A": 6},
                "S": {"A": 4, "C": 2},
                "F": {"A": 1, "B": 1, "C": 1},
            },
            "from_to": {
                "Q": {"A": {"S": {"A": 4, "C": "REST"}}},
                "S": {"A": {"F": {"A": 2, "B": 2}}, "C": {"F": {"C": 4}}},
            },
        },
        {
            "max_no_of_contestants": 48,
            "rounds": ["Q", "S", "F"],
            "no_of_heats": {
                "Q": {"A": 6},
                "S": {"A": 4, "C": 4},
                "F": {"A": 1, "B": 1, "C": 1},
            },
            "from_to": {
                "Q": {"A": {"S": {"A": 4, "C": "REST"}}},
                "S": {"A": {"F": {"A": 2, "B": 2}}, "C": {"F": {"C": 2}}},
            },
        },
        {
            "max_no_of_contestants": 56,
            "rounds": ["Q", "S", "F"],
            "no_of_heats": {
                "Q": {"A": 7},
                "S": {"A": 4, "C": 4},
                "F": {"A": 1, "B": 1, "C": 1},
            },
            "from_to": {
                "Q": {"A": {"S": {"A": 4, "C": "REST"}}},
                "S": {"A": {"F": {"A": 2, "B": 2}}, "C": {"F": {"C": 2}}},
            },
        },
        {
            "max_no_of_contestants": 80,
            "rounds": ["Q", "S", "F"],
            "no_of_heats": {
                "Q": {"A": 8},
                "S": {"A": 4, "C": 4},
                "F": {"A": 1, "B": 1, "C": 1},
            },
            "from_to": {
                "Q": {"A": {"S": {"A": 4, "C": "REST"}}},
                "S": {"A": {"F": {"A": 2, "B": 2}}, "C": {"F": {"C": 2}}},
            },
        },
    ]


@pytest.fixture
async def competition_format(race_config: Dict) -> Dict[str, Any]:
    """A competition-format for testing."""
    return {
        "id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "name": "Individual Sprint",
        "starting_order": "Draw",
        "start_procedure": "Heat Start",
        "time_between_groups": "00:15:00",
        "time_between_rounds": "00:10:00",
        "time_between_heats": "00:02:30",
        "rounds_ranked_classes": ["Q", "S", "F"],
        "rounds_non_ranked_classes": ["R1", "R2"],
        "max_no_of_contestants_in_raceclass": 80,
        "max_no_of_contestants_in_race": 10,
        "datatype": "individual_sprint",
        "race_config_non_ranked": None,
        "race_config_ranked": race_config,
    }


@pytest.fixture
async def raceclasses() -> List[Dict[str, Any]]:
    """An raceclasses object for testing."""
    return [
        {
            "id": "190e70d5-0933-4af0-bb53-1d705ba7eb95",
            "name": "G13",
            "ageclasses": ["G 13 år"],
            "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "no_of_contestants": 7,
            "ranking": True,
            "group": 1,
            "order": 1,
        },
        {
            "id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "name": "G14",
            "ageclasses": ["G 14 år"],
            "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "no_of_contestants": 8,
            "ranking": True,
            "group": 1,
            "order": 2,
        },
        {
            "id": "390e70d5-0933-4af0-bb53-1d705ba7eb95",
            "name": "J13",
            "ageclasses": ["J 13 år"],
            "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "no_of_contestants": 17,
            "ranking": True,
            "group": 1,
            "order": 3,
        },
        {
            "id": "490e70d5-0933-4af0-bb53-1d705ba7eb95",
            "name": "J14",
            "ageclasses": ["J 14 år"],
            "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "no_of_contestants": 25,
            "ranking": True,
            "group": 1,
            "order": 4,
        },
        {
            "id": "590e70d5-0933-4af0-bb53-1d705ba7eb95",
            "name": "G15",
            "ageclasses": ["G 15 år"],
            "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "no_of_contestants": 33,
            "ranking": True,
            "group": 2,
            "order": 1,
        },
        {
            "id": "690e70d5-0933-4af0-bb53-1d705ba7eb95",
            "name": "G16",
            "ageclasses": ["G 16 år"],
            "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "no_of_contestants": 41,
            "ranking": True,
            "group": 2,
            "order": 2,
        },
        {
            "id": "790e70d5-0933-4af0-bb53-1d705ba7eb95",
            "name": "J15",
            "ageclasses": ["J 15 år"],
            "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "no_of_contestants": 49,
            "ranking": True,
            "group": 2,
            "order": 3,
        },
        {
            "id": "890e70d5-0933-4af0-bb53-1d705ba7eb95",
            "name": "J16",
            "ageclasses": ["J 16 år"],
            "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "no_of_contestants": 57,
            "ranking": True,
            "group": 2,
            "order": 4,
        },
    ]


@pytest.mark.integration
@pytest.mark.asyncio
async def test_generate_raceplan_for_event(
    client: _TestClient,
    mocker: MockFixture,
    token: MockFixture,
    event: dict,
    competition_format: dict,
    raceclasses: List[dict],
    request_body: dict,
) -> None:
    """Should return 201 Created, location header."""
    RACEPLAN_ID = "290e70d5-0933-4af0-bb53-1d705ba7eb95"
    mocker.patch(
        "race_service.services.raceplans_service.create_id",
        return_value=RACEPLAN_ID,
    )
    mocker.patch(
        "race_service.adapters.raceplans_adapter.RaceplansAdapter.create_raceplan",
        return_value=RACEPLAN_ID,
    )
    mocker.patch(
        "race_service.adapters.raceplans_adapter.RaceplansAdapter.get_raceplans_by_event_id",
        return_value=[],
    )
    mocker.patch(
        "race_service.adapters.raceplans_adapter.RaceplansAdapter.get_raceplan_by_id",
        return_value=Raceplan(
            id=RACEPLAN_ID, event_id=event["id"], races=[], no_of_contestants=0
        ),
    )
    mocker.patch(
        "race_service.adapters.raceplans_adapter.RaceplansAdapter.update_raceplan",
        return_value=True,
    )
    mocker.patch(
        "race_service.adapters.races_adapter.RacesAdapter.create_race",
        return_value=str(uuid.uuid4()),
    )
    mocker.patch(
        "race_service.adapters.races_adapter.RacesAdapter.get_races_by_event_id",
        return_value=None,
    )
    mocker.patch(
        "race_service.adapters.events_adapter.EventsAdapter.get_event_by_id",
        return_value=event,
    )
    mocker.patch(
        "race_service.adapters.events_adapter.EventsAdapter.get_competition_format",
        return_value=competition_format,
    )
    mocker.patch(
        "race_service.adapters.events_adapter.EventsAdapter.get_raceclasses",
        return_value=raceclasses,
    )

    mocker.patch(
        "race_service.adapters.races_adapter.RacesAdapter.get_race_by_id",
        side_effect=races,
    )

    headers = {
        hdrs.CONTENT_TYPE: "application/json",
        hdrs.AUTHORIZATION: f"Bearer {token}",
    }

    with aioresponses(passthrough=["http://127.0.0.1"]) as m:
        m.post("http://users.example.com:8080/authorize", status=204)

        resp = await client.post(
            "/raceplans/generate-raceplan-for-event", headers=headers, json=request_body
        )
        assert resp.status == 201
        assert f"/raceplans/{RACEPLAN_ID}" in resp.headers[hdrs.LOCATION]


@pytest.fixture
async def raceclass_with_more_than_max_contestants() -> List[Dict[str, Any]]:
    """An raceclasses object for testing."""
    return [
        {
            "id": "190e70d5-0933-4af0-bb53-1d705ba7eb95",
            "name": "G13",
            "ageclasses": ["G 13 år"],
            "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
            "no_of_contestants": 81,
            "ranking": True,
            "group": 1,
            "order": 1,
        },
    ]


@pytest.mark.integration
@pytest.mark.asyncio
async def test_generate_raceplan_for_event_exceeds_max_no_of_contestants_in_raceclass(
    client: _TestClient,
    mocker: MockFixture,
    token: MockFixture,
    event: dict,
    competition_format: dict,
    raceclass_with_more_than_max_contestants: List[dict],
    request_body: dict,
) -> None:
    """Should return 400 Bad request."""
    RACEPLAN_ID = "290e70d5-0933-4af0-bb53-1d705ba7eb95"
    mocker.patch(
        "race_service.services.raceplans_service.create_id",
        return_value=RACEPLAN_ID,
    )
    mocker.patch(
        "race_service.adapters.raceplans_adapter.RaceplansAdapter.create_raceplan",
        return_value=RACEPLAN_ID,
    )
    mocker.patch(
        "race_service.adapters.raceplans_adapter.RaceplansAdapter.get_raceplans_by_event_id",
        return_value=[],
    )
    mocker.patch(
        "race_service.adapters.raceplans_adapter.RaceplansAdapter.get_raceplan_by_id",
        return_value={"id": RACEPLAN_ID},
    )
    mocker.patch(
        "race_service.adapters.raceplans_adapter.RaceplansAdapter.update_raceplan",
        return_value=True,
    )
    mocker.patch(
        "race_service.adapters.races_adapter.RacesAdapter.create_race",
        return_value=str(uuid.uuid4()),
    )
    mocker.patch(
        "race_service.adapters.races_adapter.RacesAdapter.get_races_by_event_id",
        return_value=None,
    )
    mocker.patch(
        "race_service.adapters.events_adapter.EventsAdapter.get_event_by_id",
        return_value=event,
    )
    mocker.patch(
        "race_service.adapters.events_adapter.EventsAdapter.get_competition_format",
        return_value=competition_format,
    )
    mocker.patch(
        "race_service.adapters.events_adapter.EventsAdapter.get_raceclasses",
        return_value=raceclass_with_more_than_max_contestants,
    )

    headers = {
        hdrs.CONTENT_TYPE: "application/json",
        hdrs.AUTHORIZATION: f"Bearer {token}",
    }

    with aioresponses(passthrough=["http://127.0.0.1"]) as m:
        m.post("http://users.example.com:8080/authorize", status=204)

        resp = await client.post(
            "/raceplans/generate-raceplan-for-event", headers=headers, json=request_body
        )
        assert resp.status == 400
        body = await resp.json()
        assert "Unsupported value for no of contestants" in body["detail"]


races = [
    {
        "id": "",
        "raceclass": "G13",
        "order": 1,
        "start_time": "2021-08-31T09:00:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 1,
        "rule": {"F": {"A": "ALL", "B": 0}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G14",
        "order": 2,
        "start_time": "2021-08-31T09:02:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 4,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 1,
        "rule": {"F": {"A": 4, "B": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G14",
        "order": 3,
        "start_time": "2021-08-31T09:05:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 4,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 2,
        "rule": {"F": {"A": 4, "B": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J13",
        "order": 4,
        "start_time": "2021-08-31T09:07:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 1,
        "rule": {"S": {"A": 5, "C": 0}, "F": {"C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J13",
        "order": 5,
        "start_time": "2021-08-31T09:10:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 2,
        "rule": {"S": {"A": 5, "C": 0}, "F": {"C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J13",
        "order": 6,
        "start_time": "2021-08-31T09:12:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 3,
        "rule": {"S": {"A": 5, "C": 0}, "F": {"C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 7,
        "start_time": "2021-08-31T09:15:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 1,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 8,
        "start_time": "2021-08-31T09:17:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 2,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 9,
        "start_time": "2021-08-31T09:20:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 3,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 10,
        "start_time": "2021-08-31T09:22:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 4,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J13",
        "order": 11,
        "start_time": "2021-08-31T09:32:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 1,
        "rule": {"F": {"A": 4, "B": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J13",
        "order": 12,
        "start_time": "2021-08-31T09:35:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 2,
        "rule": {"F": {"A": 4, "B": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 13,
        "start_time": "2021-08-31T09:37:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 1,
        "rule": {"F": {"C": 4}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 14,
        "start_time": "2021-08-31T09:40:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 4,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 2,
        "rule": {"F": {"C": 4}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 15,
        "start_time": "2021-08-31T09:42:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 1,
        "rule": {"F": {"A": 4, "B": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 16,
        "start_time": "2021-08-31T09:45:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 2,
        "rule": {"F": {"A": 4, "B": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G13",
        "order": 17,
        "start_time": "2021-08-31T09:55:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "A",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G14",
        "order": 18,
        "start_time": "2021-08-31T09:57:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 0,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "B",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G14",
        "order": 19,
        "start_time": "2021-08-31T10:00:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "A",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J13",
        "order": 20,
        "start_time": "2021-08-31T10:02:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 2,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "C",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J13",
        "order": 21,
        "start_time": "2021-08-31T10:05:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "B",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J13",
        "order": 22,
        "start_time": "2021-08-31T10:07:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "A",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 23,
        "start_time": "2021-08-31T10:10:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "C",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 24,
        "start_time": "2021-08-31T10:12:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "B",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J14",
        "order": 25,
        "start_time": "2021-08-31T10:15:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "A",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 26,
        "start_time": "2021-08-31T10:40:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 1,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 27,
        "start_time": "2021-08-31T10:42:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 2,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 28,
        "start_time": "2021-08-31T10:45:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 3,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 29,
        "start_time": "2021-08-31T10:47:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 4,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 30,
        "start_time": "2021-08-31T10:50:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 5,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 31,
        "start_time": "2021-08-31T10:52:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 6,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 32,
        "start_time": "2021-08-31T10:55:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 1,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 33,
        "start_time": "2021-08-31T10:57:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 2,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 34,
        "start_time": "2021-08-31T11:00:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 3,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 35,
        "start_time": "2021-08-31T11:02:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 4,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 36,
        "start_time": "2021-08-31T11:05:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 5,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 37,
        "start_time": "2021-08-31T11:07:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 6,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 38,
        "start_time": "2021-08-31T11:10:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 1,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 39,
        "start_time": "2021-08-31T11:12:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 2,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 40,
        "start_time": "2021-08-31T11:15:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 3,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 41,
        "start_time": "2021-08-31T11:17:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 4,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 42,
        "start_time": "2021-08-31T11:20:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 5,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 43,
        "start_time": "2021-08-31T11:22:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 6,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 44,
        "start_time": "2021-08-31T11:25:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 7,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 45,
        "start_time": "2021-08-31T11:27:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 1,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 46,
        "start_time": "2021-08-31T11:30:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 2,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 47,
        "start_time": "2021-08-31T11:32:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 3,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 48,
        "start_time": "2021-08-31T11:35:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 4,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 49,
        "start_time": "2021-08-31T11:37:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 5,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 50,
        "start_time": "2021-08-31T11:40:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 6,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 51,
        "start_time": "2021-08-31T11:42:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 7,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 52,
        "start_time": "2021-08-31T11:45:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "Q",
        "index": "A",
        "heat": 8,
        "rule": {"S": {"A": 4, "C": "REST"}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 53,
        "start_time": "2021-08-31T11:55:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 1,
        "rule": {"F": {"C": 4}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 54,
        "start_time": "2021-08-31T11:57:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 4,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 2,
        "rule": {"F": {"C": 4}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 55,
        "start_time": "2021-08-31T12:00:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 1,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 56,
        "start_time": "2021-08-31T12:02:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 2,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 57,
        "start_time": "2021-08-31T12:05:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 3,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 58,
        "start_time": "2021-08-31T12:07:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 4,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 59,
        "start_time": "2021-08-31T12:10:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 1,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 60,
        "start_time": "2021-08-31T12:12:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 4,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 2,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 61,
        "start_time": "2021-08-31T12:15:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 4,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 3,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 62,
        "start_time": "2021-08-31T12:17:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 4,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 4,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 63,
        "start_time": "2021-08-31T12:20:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 1,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 64,
        "start_time": "2021-08-31T12:22:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 2,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 65,
        "start_time": "2021-08-31T12:25:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 3,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 66,
        "start_time": "2021-08-31T12:27:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 4,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 67,
        "start_time": "2021-08-31T12:30:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 1,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 68,
        "start_time": "2021-08-31T12:32:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 2,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 69,
        "start_time": "2021-08-31T12:35:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 3,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 70,
        "start_time": "2021-08-31T12:37:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 5,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 4,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 71,
        "start_time": "2021-08-31T12:40:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 1,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 72,
        "start_time": "2021-08-31T12:42:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 2,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 73,
        "start_time": "2021-08-31T12:45:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 3,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 74,
        "start_time": "2021-08-31T12:47:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 4,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 75,
        "start_time": "2021-08-31T12:50:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 7,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 1,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 76,
        "start_time": "2021-08-31T12:52:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 2,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 77,
        "start_time": "2021-08-31T12:55:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 3,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 78,
        "start_time": "2021-08-31T12:57:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 6,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "C",
        "heat": 4,
        "rule": {"F": {"C": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 79,
        "start_time": "2021-08-31T13:00:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 1,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 80,
        "start_time": "2021-08-31T13:02:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 2,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 81,
        "start_time": "2021-08-31T13:05:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 3,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 82,
        "start_time": "2021-08-31T13:07:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "S",
        "index": "A",
        "heat": 4,
        "rule": {"F": {"A": 2, "B": 2}},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 83,
        "start_time": "2021-08-31T13:17:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "C",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 84,
        "start_time": "2021-08-31T13:20:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "B",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G15",
        "order": 85,
        "start_time": "2021-08-31T13:22:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "A",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 86,
        "start_time": "2021-08-31T13:25:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "C",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 87,
        "start_time": "2021-08-31T13:27:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "B",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "G16",
        "order": 88,
        "start_time": "2021-08-31T13:30:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "A",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 89,
        "start_time": "2021-08-31T13:32:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "C",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 90,
        "start_time": "2021-08-31T13:35:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "B",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J15",
        "order": 91,
        "start_time": "2021-08-31T13:37:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "A",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 92,
        "start_time": "2021-08-31T13:40:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "C",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 93,
        "start_time": "2021-08-31T13:42:30",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "B",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
    {
        "id": "",
        "raceclass": "J16",
        "order": 94,
        "start_time": "2021-08-31T13:45:00",
        "max_no_of_contestants": 10,
        "no_of_contestants": 8,
        "event_id": "290e70d5-0933-4af0-bb53-1d705ba7eb95",
        "raceplan_id": "",
        "start_entries": [],
        "results": {},
        "round": "F",
        "index": "A",
        "heat": 1,
        "rule": {},
        "datatype": "individual_sprint",
    },
]
